### ISSUE TITLE
tsconfig.app.json

### ISSUE THREAD

**Issue by sagarmonapara** [gaurav-12/angular-basics-for-beginners#1]
this project does not contain **src/tsconfig.app.json** and this file creates an issue.
after cloning this project i am install npm and run the project that does not work.

**Comment by gaurav-12** [comment]
Hello @sagarmonapara 
I have synced the project from stackblitz.com which has this issue of [not including the tsconfig.app.json](https://github.com/stackblitz/core/issues/1230).
You could try [this StackOverflow solution](https://stackoverflow.com/a/60390573). I might fix this issue later, but feel free to add a PR 🙂.

**Comment by sagarmonapara** [comment]
Hello @gaurav-12
i have tried your solution and this is worked. and update some package because the version problem.
thank you for giving solution.
